name: "test-pr"
on:
  push:
    branches: ["master", "release-*", "!*-merge-master"]
    tags: ["*"]
  pull_request:
    branches: ["master", "release-*"]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "Output context variables"
        run: |
          echo 'github.sha: ${{ github.sha }}'
          echo 'github.ref_name: ${{ github.ref_name }}'
          echo 'github.event.pull_request.head.sha: ${{ github.event.pull_request.head.sha }}'
          echo 'github.event.pull_request.id: ${{ github.event.pull_request.id }}'
          echo 'github.event.pull_request.number: ${{ github.event.pull_request.number }}'
          echo 'github.event.pull_request.merge_commit_sha: ${{ github.event.pull_request.merge_commit_sha }}'
          echo 'github.event_name: ${{ github.event_name }}'